server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/good?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 724811
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      server-addr: 42.193.22.5:8848
      discovery:
        cluster-name: CQ
  application:
    name: good-service
mybatis-plus:
  type-aliases-package: com.lx.goodservice.pojo
  configuration:
    map-underscore-to-camel-case: true #驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: status
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/*.xml
