server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/good?useSSL=false
    username: root
    password: 724811
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      server-addr: 42.193.22.5:8848
      discovery:
        cluster-name: CQ
  application:
    name: good-service
mybatis:
  type-aliases-package: com.lx.goodservice.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.lx: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS