server:
  port: 8089
oss:
  enabled: true
  type: MINIO
  endpoint: http://42.193.22.5:9000
  access-key: bully
  secret-key: LiXin-724811
  default-bucket-name: pearl-buckent
spring:
  cloud:
    nacos:
      server-addr: 42.193.22.5:8848
      discovery:
        cluster-name: CQ
  application:
    name: file-service
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB