server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?useSSL=false
    username: root
    password: 724811
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      server-addr: 42.193.22.5:8848
      discovery:
        cluster-name: CQ
  application:
    name: user-service
mybatis:
  type-aliases-package: com.lx.userservice.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.lx.com.lx.userservice: error
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS