server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user?useSSL=false
    username: root
    password: 724811
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      server-addr: 42.193.22.5:8848
      discovery:
        cluster-name: CQ
  application:
    name: user-service
mybatis-plus:
  type-aliases-package: com.lx.userservice.pojo
  configuration:
    map-underscore-to-camel-case: true #驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: status
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/*.xml
logging:
  level:
    com.lx.com.lx.userservice: error
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS